version: '3'
services:
  server:
    image: 'eepmoody/open5e-api:latest'
    build: .
    environment:
      - OPEN5E_DEBUG=${OPEN5E_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - SERVER_NAME=${SERVER_NAME}
      - CERTFILE=${CERTFILE}
      - KEYFILE=${KEYFILE}
    ports:
      - '443:8888'
    volumes:
      - .:/usr/src/open5e-api/
    depends_on:
      - watchtower
  watchtower:
    image: v2tec/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: '--interval 600 --cleanup'
  # LOCAL BUILD
  local:
    build: .
    environment:
      - OPEN5E_DEBUG=${OPEN5E_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - SERVER_NAME=${SERVER_NAME}
      - CERTFILE=${CERTFILE}
      - KEYFILE=${KEYFILE}
    ports:
      - '8888:8888'
    volumes:
      - .:/usr/src/open5e-api/
  # STAGING SERVER BUILD
  beta:
    image: 'eepmoody/open5e-api:staging'
    build: .
    environment:
      - OPEN5E_DEBUG=${OPEN5E_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - SERVER_NAME=${SERVER_NAME}
      - CERTFILE=${CERTFILE}
      - KEYFILE=${KEYFILE}
    ports:
      - '443:8888'
    volumes:
      - .:/usr/src/open5e-api/
    depends_on:
      - watchtower
