[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:elasticsearch]
command=/usr/share/elasticsearch/bin/elasticsearch
user=elasticsearch
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/elasticsearch/stdout.log
stderr_logfile=/var/log/elasticsearch/stderr.log
environment=ES_JAVA_OPTS="-Xms512m -Xmx512m"

[program:gunicorn]
directory=/opt/services/open5e-api
command=/usr/local/bin/pipenv run gunicorn -b :8080 --workers 2 --timeout 120 server.wsgi:application
autostart=false
autorestart=true
startretries=3
stdout_logfile=/var/log/gunicorn/stdout.log
stderr_logfile=/var/log/gunicorn/stderr.log
environment=ELASTICSEARCH_URL="http://127.0.0.1:9200/"


