# Generated by Django 2.1 on 2019-07-09 01:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_auto_20180826_1613'), ('api', '0003_remove_race_subtypes'), ('api', '0004_auto_20180826_2043'), ('api', '0005_auto_20180828_0106'), ('api', '0006_monster_speed_json'), ('api', '0007_remove_monster_speed_json'), ('api', '0008_auto_20180903_0344'), ('api', '0009_magicitem'), ('api', '0010_background_feature_desc'), ('api', '0011_auto_20180921_0233'), ('api', '0012_subrace_asi_json'), ('api', '0013_auto_20180921_0257'), ('api', '0014_auto_20180926_2101'), ('api', '0015_auto_20181112_0537'), ('api', '0016_monster_skills'), ('api', '0017_remove_monster_skills'), ('api', '0018_monster_skills_json')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_proficiencies', models.TextField()),
                ('languages', models.TextField()),
                ('equipment', models.TextField()),
                ('feature', models.TextField()),
                ('suggested_characteristics', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_dice', models.TextField()),
                ('hp_at_1st_level', models.TextField()),
                ('hp_at_higher_levels', models.TextField()),
                ('prof_armor', models.TextField()),
                ('prof_weapons', models.TextField()),
                ('prof_tools', models.TextField()),
                ('prof_saving_throws', models.TextField()),
                ('prof_skills', models.TextField()),
                ('equipment', models.TextField()),
                ('table', models.TextField()),
                ('spellcasting_ability', models.TextField()),
                ('subtypes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('license', models.TextField()),
                ('author', models.TextField()),
                ('organization', models.TextField()),
                ('version', models.TextField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisite', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('route', models.TextField(default='conditions/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.TextField()),
                ('type', models.TextField()),
                ('subtype', models.TextField()),
                ('alignment', models.TextField()),
                ('armor_class', models.IntegerField(default=12)),
                ('hit_points', models.IntegerField(null=True)),
                ('hit_dice', models.TextField()),
                ('speed_json', models.TextField()),
                ('strength', models.IntegerField(null=True)),
                ('dexterity', models.IntegerField(null=True)),
                ('constitution', models.IntegerField(null=True)),
                ('intelligence', models.IntegerField(null=True)),
                ('wisdom', models.IntegerField(null=True)),
                ('charisma', models.IntegerField(null=True)),
                ('constitution_save', models.IntegerField(null=True)),
                ('intelligence_save', models.IntegerField(null=True)),
                ('wisdom_save', models.IntegerField(null=True)),
                ('perception', models.IntegerField(null=True)),
                ('damage_vulnerabilities', models.TextField()),
                ('damage_resistances', models.TextField()),
                ('damage_immunities', models.TextField()),
                ('condition_immunities', models.TextField()),
                ('senses', models.TextField()),
                ('languages', models.TextField()),
                ('challenge_rating', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('route', models.TextField(default='monsters/')),
                ('actions_json', models.TextField(default='')),
                ('legendary_actions_json', models.TextField(default='')),
                ('reactions_json', models.TextField(default='')),
                ('special_abilities_json', models.TextField(default='')),
                ('charisma_save', models.IntegerField(null=True)),
                ('dexterity_save', models.IntegerField(null=True)),
                ('strength_save', models.IntegerField(null=True)),
                ('armor_desc', models.TextField(null=True)),
                ('group', models.TextField(null=True)),
                ('skills_json', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('route', models.TextField(default='planes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asi_desc', models.TextField()),
                ('asi', models.TextField()),
                ('age', models.TextField()),
                ('alignment', models.TextField()),
                ('size', models.TextField()),
                ('speed', models.TextField()),
                ('speed_desc', models.TextField()),
                ('languages', models.TextField()),
                ('vision', models.TextField()),
                ('traits', models.TextField()),
                ('subtypes', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('parent', models.TextField(null=True)),
                ('route', models.TextField(default='sections/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('higher_level', models.TextField()),
                ('page', models.TextField()),
                ('range', models.TextField()),
                ('components', models.TextField()),
                ('material', models.TextField()),
                ('ritual', models.TextField()),
                ('duration', models.TextField()),
                ('concentration', models.TextField()),
                ('casting_time', models.TextField()),
                ('level', models.TextField()),
                ('school', models.TextField()),
                ('dnd_class', models.TextField()),
                ('archetype', models.TextField()),
                ('circles', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('route', models.TextField(default='spells/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asi_desc', models.TextField()),
                ('traits', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('parent_race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='api.Race')),
                ('route', models.TextField(default='subraces/')),
                ('asi_json', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.AddField(
            model_name='charclass',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.AddField(
            model_name='background',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='char_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='api.CharClass'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.RemoveField(
            model_name='race',
            name='subtypes',
        ),
        migrations.RenameField(
            model_name='charclass',
            old_name='subtypes',
            new_name='subtypes_name',
        ),
        migrations.AddField(
            model_name='archetype',
            name='route',
            field=models.TextField(default='archetypes/'),
        ),
        migrations.AddField(
            model_name='background',
            name='route',
            field=models.TextField(default='backgrounds/'),
        ),
        migrations.AddField(
            model_name='charclass',
            name='route',
            field=models.TextField(default='classes/'),
        ),
        migrations.AddField(
            model_name='condition',
            name='route',
            field=models.TextField(default='conditions/'),
        ),
        migrations.AddField(
            model_name='race',
            name='route',
            field=models.TextField(default='races/'),
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.TextField()),
                ('rarity', models.TextField()),
                ('requires_attunement', models.TextField()),
                ('route', models.TextField(default='magicitems/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='background',
            name='feature_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='race',
            old_name='asi',
            new_name='asi_json',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='speed',
            new_name='speed_json',
        ),
    ]
