# Generated by Django 2.1.5 on 2019-10-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='copyright',
            field=models.TextField(null=True),
        ),
    ]
