# Generated by Django 2.1 on 2019-07-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0018_monster_skills_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='legendary_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monster',
            name='actions_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='legendary_actions_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='reactions_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skills_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='special_abilities_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='asi_json',
            field=models.TextField(),
        ),
    ]
