# Generated by Django 5.2.9 on 2026-02-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_v2_related_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
