# Generated by Django 2.1 on 2019-07-18 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190709_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.TextField(default='weapons/')),
                ('category', models.TextField()),
                ('cost', models.TextField()),
                ('damage_dice', models.TextField()),
                ('damage_type', models.TextField()),
                ('weight', models.TextField()),
                ('properties_json', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
