# Generated by Django 5.2.1 on 2025-05-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_v2_related_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
