# Generated by Django 2.1.11 on 2019-11-10 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='charclass',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='magicitem',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
