# Generated by Django 2.1.11 on 2019-10-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_armor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='plus_con_mod',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='plus_dex_mod',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='plus_flat_mod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='plus_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='plus_wis_mod',
            field=models.BooleanField(null=True),
        ),
    ]
