# Generated by Django 2.1 on 2019-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='img_main',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
