# Generated by Django 2.1.11 on 2019-10-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191029_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='strength_requirement',
            field=models.IntegerField(null=True),
        ),
    ]
