# Generated by Django 2.1.11 on 2022-07-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191110_1830'),
        ('api', '0005_auto_20191029_0216'),
    ]

    operations = [
    ]
