# Generated by Django 2.1 on 2019-09-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190901_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='spell',
            name='level_int',
            field=models.IntegerField(null=True),
        ),
    ]
