# Generated by Django 2.1.11 on 2022-07-05 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20220705_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
