# Generated by Django 2.1 on 2019-09-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190903_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={},
        ),
    ]
