# Generated by Django 2.1.5 on 2019-10-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190903_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='tool_proficiencies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='languages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='skill_proficiencies',
            field=models.TextField(null=True),
        ),
    ]
