# Generated by Django 2.1.11 on 2023-03-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='cr',
            field=models.FloatField(null=True),
        ),
    ]
