# Generated by Django 2.1.5 on 2019-10-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_monster_spells_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='spells_json',
            field=models.TextField(default=''),
        ),
    ]
