# Generated by Django 2.1.11 on 2023-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_monster_cr'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='armor',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='background',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='charclass',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='magicitem',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plane',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subrace',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
    ]
