# Generated by Django 2.1.5 on 2019-10-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191019_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='spells_json',
            field=models.TextField(),
        ),
    ]
