# Generated by Django 2.1.11 on 2023-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230318_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='effects_desc_json',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feat',
            name='prerequisite',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='route',
            field=models.TextField(default='feats/'),
        ),
    ]
