# Generated by Django 2.1.5 on 2019-10-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_document_license_url'),
        ('api', '0011_auto_20191019_1814'),
    ]

    operations = [
    ]
