# Generated by Django 3.2.18 on 2023-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230320_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='can_be_cast_as_ritual',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='challenge_rating',
            field=models.TextField(help_text='Monster challenge rating.'),
        ),
        migrations.AlterField(
            model_name='monsterspell',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
