# Generated by Django 2.1.5 on 2019-10-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20191019_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='spells',
            field=models.ManyToManyField(to='api.Spell'),
        ),
    ]
