# Generated by Django 3.2.18 on 2023-04-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230414_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='ritual',
        ),
    ]
