# Generated by Django 2.1.5 on 2019-10-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_monster_spells'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='spells',
            new_name='spell_list',
        ),
    ]
