# Generated by Django 3.2.18 on 2023-04-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230413_0149'),
        ('api', '0013_remove_spell_ritual'),
    ]

    operations = [
    ]
