# Generated by Django 3.2.18 on 2023-04-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20230414_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='can_be_cast_as_ritual',
            field=models.BooleanField(help_text='Whether or not the spell can be cast as a ritual.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level_int',
            field=models.IntegerField(default=0, help_text='Integer representing the level of the spell. Cantrip is 0.'),
            preserve_default=False,
        ),
    ]
