# Generated by Django 2.1.5 on 2019-10-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191019_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='monster',
            name='spell_list',
        ),
        migrations.AddField(
            model_name='monsterspell',
            name='monster',
            field=models.ForeignKey(on_delete='CASCADE', to='api.Monster'),
        ),
        migrations.AddField(
            model_name='monsterspell',
            name='spell',
            field=models.ForeignKey(on_delete='CASCADE', to='api.Spell'),
        ),
    ]
