# Generated by Django 2.1 on 2019-07-09 00:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181112_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='skills',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
