# Generated by Django 2.1.5 on 2019-10-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191019_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='spell_list',
            field=models.ManyToManyField(related_name='monsters', through='api.MonsterSpell', to='api.Spell'),
        ),
    ]
