# Generated by Django 2.1.5 on 2019-10-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_monster_spell_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterspell',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Monster'),
        ),
        migrations.AlterField(
            model_name='monsterspell',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Spell'),
        ),
    ]
