# Generated by Django 3.2.18 on 2023-04-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_spell_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='concentration',
        ),
        migrations.AddField(
            model_name='spell',
            name='requires_concentration',
            field=models.BooleanField(default=True, help_text='Whether the spell requires concentration'),
            preserve_default=False,
        ),
    ]
