# Generated by Django 2.1 on 2019-07-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_monster_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='skills_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
