# Generated by Django 3.2.18 on 2023-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230414_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='target_range_in_feet',
            field=models.IntegerField(default=10, help_text='Distance from the caster to the target in feet.'),
            preserve_default=False,
        ),
    ]
