# Generated by Django 3.2.18 on 2023-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_spell_target_range_in_feet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='target_range_in_feet',
        ),
        migrations.AddField(
            model_name='spell',
            name='target_range_sort',
            field=models.IntegerField(default=1, help_text='Sortable distance ranking to the target.'),
            preserve_default=False,
        ),
    ]
