# Generated by Django 3.2.18 on 2023-04-16 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_spell_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.TextField(help_text='Text description of the target range.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spell_level',
            field=models.IntegerField(help_text='Integer representing the level of the spell. Cantrip is 0.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target_range_sort',
            field=models.IntegerField(help_text='Sortable distance ranking to the target.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
