# Generated by Django 3.2.18 on 2023-04-16 14:12

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20230416_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.TextField(help_text='Representation of the school of magic, such as "illusion" or "evocation".', validators=[api.validators.spell_school_validator]),
        ),
    ]
