# Generated by Django 3.2.18 on 2023-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_spell_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='can_be_cast_as_ritual',
            field=models.BooleanField(default=False, help_text='Whether or not the spell can be cast as a ritual.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='requires_concentration',
            field=models.BooleanField(default=False, help_text='Whether the spell requires concentration'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='requires_material_components',
            field=models.BooleanField(default=False, help_text='Casting this spell requires material components.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='requires_somatic_components',
            field=models.BooleanField(default=False, help_text='Casting this spell requires somatic components.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='requires_verbal_components',
            field=models.BooleanField(default=False, help_text='Casting this spell requires verbal components.'),
        ),
    ]
