# Generated by Django 3.2.18 on 2023-05-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20230513_1436'),
        ('api', '0027_alter_spelllist_spells'),
    ]

    operations = [
    ]
