# Generated by Django 3.2.19 on 2023-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20230516_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='environments',
            field=models.TextField(null=True),
        ),
    ]
