# Generated by Django 3.2.19 on 2023-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_monster_environments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='environments',
            field=models.TextField(help_text='String list of environments that the monster can be found in.', null=True),
        ),
    ]
