# Generated by Django 3.2.19 on 2023-05-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_monster_environments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='environments',
            new_name='environments_json',
        ),
    ]
