# Generated by Django 3.2.19 on 2023-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_environments_monster_environments_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='size_raw',
            field=models.TextField(default='Medium', help_text='Size Category.'),
        ),
    ]
