# Generated by Django 3.2.20 on 2023-10-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_race_size_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='bonus_actions_json',
            field=models.TextField(default=None),
        ),
    ]
