# Generated by Django 3.2.20 on 2023-11-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_monster_bonus_actions_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='parent',
            field=models.TextField(null=True),
        ),
    ]
