# Generated by Django 3.2.20 on 2024-01-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_plane_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='lair_actions_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='lair_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='mythic_actions_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
