# Generated by Django 3.2.20 on 2024-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_plane_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='reactions_json',
            field=models.TextField(null=True),
        ),
    ]
