# Generated by Django 3.2.20 on 2023-12-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_plane_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='size_rating',
            field=models.IntegerField(default=0, help_text='Monster size category as number 0 is tiny, 1 is small, 2 is large, 3 is huge, 4 is gargantuan and 5 is titanic.'),
            preserve_default=False,
        ),
    ]
