# Generated by Django 3.2.20 on 2023-12-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_monster_size_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='size_rating',
            field=models.IntegerField(default=-1, help_text='Monster size category as number 0 is tiny, 1 is small, 2 is large, 3 is huge, 4 is gargantuan and 5 is titanic. default is -1 which is unknown'),
        ),
    ]
