# Generated by Django 3.2.20 on 2024-03-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_monster_legendary_actions_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='legendary_desc',
            field=models.TextField(null=True),
        ),
    ]
