name: open5e-api-test-elasticsearch
workers:
  - name: elasticsearch
    image:
      registry_type: DOCKER_HUB
      repository: elasticsearch
      tag: "8.11.0"
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: elasticsearch -E discovery.type=single-node -E xpack.security.enabled=false -E network.host=0.0.0.0
    envs:
      - key: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m -Des.entitlements.enabled=false"
    liveness_health_check:
      http_path: "/_cluster/health"
      port: 9200
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

services:
  - name: api
    github:
      repo: open5e/open5e-api
      branch: main
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: ELASTICSEARCH_URL
        value: "http://elasticsearch:9200/"
    health_check:
      http_path: "/"
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
