# Generated by Django 3.2.19 on 2023-06-06 20:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0031_rename_environments_monster_environments_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorType',
            fields=[
                ('slug', models.CharField(default=uuid.uuid1, help_text='Short name for the game content item.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(help_text='Name of the game content item.')),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_no', models.IntegerField(null=True)),
                ('is_light', models.BooleanField(default=False, help_text='If the armor is light.')),
                ('is_medium', models.BooleanField(default=False, help_text='If the armor is medium.')),
                ('is_heavy', models.BooleanField(default=False, help_text='If the armor is heavy.')),
                ('grants_stealth_disadvantage', models.BooleanField(default=False, help_text='If the armor results in disadvantage on stealth checks.')),
                ('strength_score_required', models.IntegerField(help_text='Strength score required to wear the armor without penalty.', null=True)),
                ('ac_base', models.IntegerField(help_text='Integer representing the armor class without modifiers.')),
                ('ac_add_dexmod', models.BooleanField(default=False, help_text='If the final armor class includes dexterity modifier.')),
                ('ac_cap_dexmod', models.IntegerField(help_text='Integer representing the dexterity modifier cap.', null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('slug', models.CharField(default=uuid.uuid1, help_text='Short name for the game content item.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(help_text='Name of the game content item.')),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_no', models.IntegerField(null=True)),
                ('size', models.IntegerField(choices=[(1, 'Tiny'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Huge'), (6, 'Gargantuan')], help_text='Integer representing the size of the object.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('weight', models.DecimalField(decimal_places=3, help_text='Number representing the weight of the object.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('armor_class', models.IntegerField(help_text='Integer representing the armor class of the object.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hit_points', models.IntegerField(help_text='Integer representing the hit points of the object.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('damage_immunities', models.JSONField(default=[], help_text='List of damage types that this is immune to.')),
                ('damage_resistances', models.JSONField(default=[], help_text='List of damage types that this is resistant to.')),
                ('damage_vulnerabilities', models.JSONField(default=[], help_text='List of damage types that this is vulnerable to.')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Number representing the cost of the object.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_magical', models.BooleanField(default=False, help_text='If the item is a magical item.')),
                ('armor_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.armortype')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.item')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('slug', models.CharField(default=uuid.uuid1, help_text='Short name for the game content item.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(help_text='Name of the game content item.')),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_no', models.IntegerField(null=True)),
                ('damage_type', models.TextField(default='bludgeoning', help_text='The damage type dealt by attacks with the weapon.')),
                ('damage_dice', models.TextField(help_text='The damage dice when used making an attack.', null=True)),
                ('versatile_dice', models.TextField(help_text='The damage dice when attacking using versatile.', null=True)),
                ('range_reach', models.IntegerField(default=5, help_text='The range of the weapon when making a melee attack.', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_finesse', models.BooleanField(default=False, help_text='If the weapon is finesse.')),
                ('is_thrown', models.BooleanField(default=False, help_text='If the weapon is thrown.')),
                ('is_two_handed', models.BooleanField(default=False, help_text='If the weapon is two-handed.')),
                ('is_versatile', models.BooleanField(default=False, help_text='If the weapon is versatile.')),
                ('requires_ammunition', models.BooleanField(default=False, help_text='If the weapon requires ammunition.')),
                ('requires_loading', models.BooleanField(default=False, help_text='If the weapon requires loading.')),
                ('is_heavy', models.BooleanField(default=False, help_text='If the weapon is heavy.')),
                ('is_light', models.BooleanField(default=False, help_text='If the weapon is light.')),
                ('is_lance', models.BooleanField(default=False, help_text='If the weapon is a lance.')),
                ('is_net', models.BooleanField(default=False, help_text='If the weapon is a net.')),
                ('is_simple', models.BooleanField(default=False, help_text='If the weapon category is simple.')),
                ('is_martial', models.BooleanField(default=False, help_text='If the weapon is category is martial.')),
                ('is_improvised', models.BooleanField(default=False, help_text='If the weapon is improvised.')),
                ('range_normal', models.IntegerField(help_text='The normal range of a ranged weapon attack.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('range_long', models.IntegerField(help_text='The long range of a ranged weapon attack.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('slug', models.CharField(default=uuid.uuid1, help_text='Short name for the game content item.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(help_text='Name of the game content item.')),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_no', models.IntegerField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
                ('items', models.ManyToManyField(through='api_v2.ItemQuantity', to='api_v2.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='itemset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.itemset'),
        ),
        migrations.AddField(
            model_name='item',
            name='weapon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.weapontype'),
        ),
    ]
