# Generated by Django 3.2.19 on 2023-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='damage_immunities',
            field=models.JSONField(default=list, help_text='List of damage types that this is immune to.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_resistances',
            field=models.JSONField(default=list, help_text='List of damage types that this is resistant to.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_vulnerabilities',
            field=models.JSONField(default=list, help_text='List of damage types that this is vulnerable to.'),
        ),
    ]
