# Generated by Django 5.1.1 on 2024-10-09 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatureactionattack',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('feet', 'feet'), ('miles', 'miles')], help_text='What distance unit the relevant field uses.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creatureaction',
            name='legendary_cost',
            field=models.SmallIntegerField(blank=True, default=None, help_text='null if not legendary, else, the number of legendary actions this costs.', null=True),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='long_range_ft',
            field=models.FloatField(blank=True, help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='range_ft',
            field=models.FloatField(blank=True, help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='reach_ft',
            field=models.FloatField(blank=True, help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
