# Generated by Django 3.2.19 on 2023-06-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='license',
        ),
        migrations.AddField(
            model_name='document',
            name='licenses',
            field=models.ManyToManyField(help_text='Licenses that the content has been released under.', to='api_v2.License'),
        ),
    ]
