# Generated by Django 5.1.1 on 2024-10-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_creatureactionattack_distance_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatureactionattack',
            old_name='long_range_ft',
            new_name='long_range',
        ),
        migrations.RenameField(
            model_name='creatureactionattack',
            old_name='range_ft',
            new_name='range',
        ),
        migrations.RenameField(
            model_name='creatureactionattack',
            old_name='reach_ft',
            new_name='reach',
        ),
    ]
