# Generated by Django 3.2.19 on 2023-06-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_auto_20230618_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('staff', 'Staff'), ('rod', 'Rod'), ('scroll', 'Scroll'), ('potion', 'Potion'), ('wand', 'Wand'), ('wondrous-item', 'Wondrous item'), ('ring', 'Ring'), ('ammunition', 'Ammunition'), ('weapon', 'Weapon'), ('armor', 'Armor'), ('gem', 'Gem'), ('jewelry', 'Jewelry'), ('art', 'Art'), ('trade-good', 'Trade Good'), ('shield', 'Shield'), ('poison', 'Poison')], default='weapon', help_text='The category of the magic item.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armor',
            name='ac_cap_dexmod',
            field=models.IntegerField(blank=True, help_text='Integer representing the dexterity modifier cap.', null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='strength_score_required',
            field=models.IntegerField(blank=True, help_text='Strength score required to wear the armor without penalty.', null=True),
        ),
    ]
