# Generated by Django 3.2.19 on 2023-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_auto_20230618_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='ac_cap_dexmod',
            field=models.IntegerField(blank=True, help_text='Integer representing the dexterity modifier cap.', null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='strength_score_required',
            field=models.IntegerField(blank=True, help_text='Strength score required to wear the armor without penalty.', null=True),
        ),
    ]
