# Generated by Django 5.1.1 on 2024-10-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_rulegroup_rule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RuleGroup',
            new_name='RuleSet',
        ),
    ]
