# Generated by Django 3.2.19 on 2023-06-14 19:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_environments_monster_environments_json'),
        ('api_v2', '0002_auto_20230606_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_magical',
        ),
        migrations.RemoveField(
            model_name='weapontype',
            name='is_martial',
        ),
        migrations.CreateModel(
            name='MagicItemType',
            fields=[
                ('slug', models.CharField(default=uuid.uuid1, help_text='Short name for the game content item.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(help_text='Name of the game content item.')),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_no', models.IntegerField(null=True)),
                ('requires_attunement', models.BooleanField(default=False, help_text='If the item requires attunement.')),
                ('rarity', models.IntegerField(choices=[(1, 'common'), (2, 'uncommon'), (3, 'rare'), (4, 'very rare'), (5, 'legendary')], help_text='Integer representing the rarity of the object.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='magic_item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.magicitemtype'),
        ),
    ]
