# Generated by Django 3.2.20 on 2023-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0003_race_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='prerequisite_desc',
            field=models.CharField(blank=True, help_text='Prerequisite for the game content item.', max_length=200),
        ),
    ]
