# Generated by Django 3.2.19 on 2023-07-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_alter_item_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
                ('items', models.ManyToManyField(help_text='The set of items.', to='api_v2.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
