# Generated by Django 3.2.20 on 2023-08-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_alter_feat_prerequisite_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ['pk']},
        ),
    ]
