# Generated by Django 5.1.1 on 2024-10-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_alter_size_space_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('feet', 'feet'), ('miles', 'miles')], help_text='What distance unit the relevant field uses.', max_length=20, null=True),
        ),
    ]
