# Generated by Django 3.2.19 on 2023-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0005_itemset'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemset',
            name='name',
            field=models.CharField(default=None, help_text='Name of the item.', max_length=100),
            preserve_default=False,
        ),
    ]
