# Generated by Django 3.2.20 on 2023-08-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0007_featbenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featbenefit',
            name='desc',
            field=models.TextField(help_text='Text of the individual feat benefit.'),
        ),
    ]
