# Generated by Django 3.2.20 on 2023-09-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0008_alter_featbenefit_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_trait_table', models.TextField(help_text='Table to roll for personality traits. Markdown.')),
                ('ideal_table', models.TextField(help_text='Table to roll for ideals. Markdown.')),
                ('bond_table', models.TextField(help_text='Table to roll for bonds. Markdown.')),
                ('flaw_table', models.TextField(help_text='Table to roll for flaws. Markdown.')),
            ],
        ),
        migrations.AlterField(
            model_name='featbenefit',
            name='desc',
            field=models.TextField(help_text='Description of the game content item. Markdown.'),
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.suggestedcharacteristics')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
            ],
            options={
                'verbose_name_plural': 'backgrounds',
            },
        ),
    ]
