# Generated by Django 5.1.1 on 2024-10-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_alter_rule_index_alter_rule_initialheaderlevel_and_more'),
        ('api_v2', '0008_weapon_distance_unit'),
    ]

    operations = [
    ]
