# Generated by Django 3.2.20 on 2023-10-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0008_alter_featbenefit_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatureaction',
            options={},
        ),
    ]
