# Generated by Django 5.1.1 on 2024-10-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0009_merge_20241010_0144'),
        ('api_v2', '0009_merge_20241010_0919'),
    ]

    operations = [
    ]
