# Generated by Django 3.2.20 on 2023-09-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0009_auto_20230917_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuggestedCharacteristics',
            new_name='Characteristics',
        ),
    ]
