# Generated by Django 5.1.2 on 2024-10-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0010_merge_20241016_1952'),
        ('api_v2', '0010_spellcastingoption_concentration_and_more'),
    ]

    operations = [
    ]
