# Generated by Django 3.2.20 on 2023-10-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0011_creatureset_creaturetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='deprecated_type',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='subtype',
        ),
    ]
