# Generated by Django 3.2.20 on 2023-09-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0012_auto_20230917_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.background')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
