# Generated by Django 3.2.20 on 2023-10-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0012_auto_20231029_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='type',
            field=models.ForeignKey(default='humanoid', help_text='Type of creature, such as Aberration.', on_delete=django.db.models.deletion.CASCADE, to='api_v2.creaturetype'),
            preserve_default=False,
        ),
    ]
