# Generated by Django 5.1.2 on 2024-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0012_alter_creature_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='suggested_hit_dice',
            field=models.CharField(blank=True, choices=[('D4', 'd4'), ('D6', 'd6'), ('D8', 'd8'), ('D10', 'd10'), ('D12', 'd12'), ('D20', 'd20')], help_text='What kind of die to roll for damage.', max_length=20, null=True),
        ),
    ]
