# Generated by Django 5.1.2 on 2024-10-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0013_size_suggested_hit_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='interior',
            field=models.BooleanField(default=False, help_text='Whether or not this environment is an interior space.'),
        ),
    ]
