# Generated by Django 5.1.2 on 2024-10-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0014_environment_interior'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='environments',
            field=models.ManyToManyField(related_name='creature_environments', to='api_v2.environment'),
        ),
    ]
