# Generated by Django 5.1.2 on 2024-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0016_alter_creaturetrait_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='saving_throws',
            field=models.ManyToManyField(help_text='Saving throw proficiencies for this class.', related_name='characterclass_saving_throws', to='api_v2.ability'),
        ),
    ]
