# Generated by Django 3.2.20 on 2023-11-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0013_creature_type'),
        ('api_v2', '0017_auto_20231006_1953'),
    ]

    operations = [
    ]
