# Generated by Django 5.1.2 on 2024-11-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0017_characterclass_saving_throws'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='caster_type',
            field=models.CharField(blank=True, choices=[('FULL', 'Full'), ('HALF', 'Half'), ('NONE', 'None')], default=None, help_text='Type of caster. Options are full, half, none.', max_length=100, null=True),
        ),
    ]
