# Generated by Django 5.1.2 on 2024-12-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0018_characterclass_caster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeatureitem',
            name='column',
            field=models.BooleanField(default=False, help_text='Whether or not the field should be displayed as a column.'),
            preserve_default=False,
        ),
    ]
