# Generated by Django 5.1.2 on 2024-12-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0019_classfeatureitem_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeatureitem',
            name='column',
        ),
        migrations.AddField(
            model_name='classfeatureitem',
            name='column_value',
            field=models.CharField(blank=True, help_text='The value that should be displayed in the table column (where applicable).', max_length=20, null=True),
        ),
    ]
