# Generated by Django 3.2.20 on 2023-11-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0019_damagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('is_exotic', models.BooleanField(default=False, help_text='Whether or not the language is exotic.')),
                ('is_secret', models.BooleanField(default=False, help_text='Whether or not the language is secret.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
                ('script_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
