# Generated by Django 5.1.2 on 2025-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0020_remove_classfeatureitem_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='initiative_bonus',
            field=models.SmallIntegerField(blank=True, help_text='Initiative bonus override. If not set, defaults to dexterity modifier.', null=True),
        ),
    ]
