# Generated by Django 5.1.2 on 2025-02-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0020_remove_classfeatureitem_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='stats_expected',
        ),
    ]
