# Generated by Django 5.1.2 on 2025-03-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0021_creature_initiative_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='initiative_bonus',
        ),
        migrations.AddField(
            model_name='creature',
            name='_initiative_bonus',
            field=models.SmallIntegerField(blank=True, db_column='initiative_bonus', help_text='Initiative bonus. If not set, defaults to dexterity modifier.', null=True),
        ),
    ]
