# Generated by Django 5.1.2 on 2025-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0021_remove_document_stats_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeatureitem',
            name='detail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
