# Generated by Django 5.1.2 on 2025-03-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0022_remove_creature_initiative_bonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='_initiative_bonus',
            new_name='initiative_bonus',
        ),
    ]
