# Generated by Django 5.1.2 on 2025-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0022_classfeatureitem_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeatureitem',
            name='detail',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
