# Generated by Django 3.2.20 on 2023-11-04 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0022_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_text',
        ),
    ]
