# Generated by Django 3.2.20 on 2023-11-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0023_rename_category_item_category_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
