# Generated by Django 5.1.2 on 2025-03-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0024_alter_classfeatureitem_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='initiative_bonus',
            field=models.SmallIntegerField(blank=True, help_text='Initiative bonus. If not set, defaults to dexterity modifier.', null=True),
        ),
    ]
