# Generated by Django 3.2.20 on 2023-11-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0024_itemcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='key',
            field=models.CharField(default='key', help_text='Unique key for the ItemCategory.', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
