# Generated by Django 5.1.2 on 2025-03-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0025_creature_initiative_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
