# Generated by Django 5.1.2 on 2025-03-16 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0025_creature_initiative_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('keywords', models.TextField(help_text='List of keywords, to be used by the search index.')),
                ('file_path', models.TextField(help_text='Relative path of the file, to be used in static file resolution.')),
                ('type', models.CharField(blank=True, choices=[('icon', 'Icon'), ('illustration', 'Illustration')], help_text='What type image this is, such as icon or illustration.', max_length=20, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
