# Generated by Django 3.2.20 on 2023-11-05 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0025_auto_20231105_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='document',
            field=models.ForeignKey(default='srd', on_delete=django.db.models.deletion.CASCADE, to='api_v2.document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False),
        ),
    ]
