# Generated by Django 5.1.2 on 2025-03-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0026_delete_searchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeatureitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='api_v2.classfeature'),
        ),
    ]
