# Generated by Django 5.1.2 on 2025-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0026_delete_searchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='armor_detail',
            field=models.CharField(default=False, help_text='Represents parathetical text that follows an objects AC', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='armor_detail',
            field=models.CharField(default=False, help_text='Represents parathetical text that follows an objects AC', max_length=64, null=True),
        ),
    ]
