# Generated by Django 5.1.2 on 2025-03-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0026_delete_searchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureaction',
            name='parent',
            field=models.ForeignKey(help_text='The creature to which this action belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api_v2.creature'),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='parent',
            field=models.ForeignKey(help_text='The creature action to which this attack belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='api_v2.creatureaction'),
        ),
    ]
