# Generated by Django 5.1.2 on 2025-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0027_creature_armor_detail_item_armor_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='armor_detail',
            field=models.CharField(default='', help_text='Represents parathetical text that follows an objects AC', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='armor_detail',
            field=models.CharField(default='', help_text='Represents parathetical text that follows an objects AC', max_length=64, null=True),
        ),
    ]
