# Generated by Django 3.2.20 on 2023-11-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0027_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_text',
            field=models.CharField(choices=[('staff', 'Staff'), ('rod', 'Rod'), ('scroll', 'Scroll'), ('potion', 'Potion'), ('wand', 'Wand'), ('wondrous-item', 'Wondrous item'), ('ring', 'Ring'), ('ammunition', 'Ammunition'), ('weapon', 'Weapon'), ('armor', 'Armor'), ('gem', 'Gem'), ('jewelry', 'Jewelry'), ('art', 'Art'), ('trade-good', 'Trade Good'), ('shield', 'Shield'), ('poison', 'Poison'), ('adventuring-gear', 'Adventuring gear'), ('tools', 'Tools')], help_text='The category of the magic item.', max_length=100, null=True),
        ),
    ]
