# Generated by Django 5.1.2 on 2025-03-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0027_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.image'),
        ),
    ]
