# Generated by Django 5.1.2 on 2025-03-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0027_alter_classfeatureitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api_v2.characterclass'),
        ),
    ]
