# Generated by Django 3.2.20 on 2023-11-05 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0028_alter_item_category_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_text',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='pooop', on_delete=django.db.models.deletion.CASCADE, to='api_v2.itemcategory'),
            preserve_default=False,
        ),
    ]
