# Generated by Django 5.1.2 on 2025-04-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0027_alter_creatureaction_parent_and_more'),
        ('api_v2', '0028_alter_classfeature_parent'),
    ]

    operations = [
    ]
