# Generated by Django 5.1.2 on 2025-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0029_merge_20250407_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatureaction',
            name='order',
            field=models.SmallIntegerField(blank=True, help_text='The position in the list of features that a feature appears in its source statblock', null=True),
        ),
    ]
