# Generated by Django 5.1.2 on 2025-04-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0028_condition_icon'),
        ('api_v2', '0029_merge_20250407_1910'),
    ]

    operations = [
    ]
