# Generated by Django 3.2.20 on 2023-11-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0029_auto_20231105_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('type', models.CharField(blank=True, choices=[('ability_score', 'Ability Score Increase or Decrease'), ('skill_proficiency', 'Skill Proficiency'), ('tool_proficiency', 'Tool Proficiency'), ('language', 'Language'), ('equipment', 'Equipment'), ('feature', 'Feature'), ('suggested_characteristics', 'Suggested Characteristics'), ('adventures_and_advancement', 'Adventures and Advancement'), ('connection_and_memento', 'Connection and Memento')], help_text='Modification type.', max_length=200, null=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.background')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('type', models.CharField(blank=True, choices=[('ability_score', 'Ability Score Increase or Decrease'), ('skill_proficiency', 'Skill Proficiency'), ('tool_proficiency', 'Tool Proficiency'), ('language', 'Language'), ('equipment', 'Equipment'), ('feature', 'Feature'), ('suggested_characteristics', 'Suggested Characteristics'), ('adventures_and_advancement', 'Adventures and Advancement'), ('connection_and_memento', 'Connection and Memento')], help_text='Modification type.', max_length=200, null=True)),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.feat')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='featbenefit',
            name='feat',
        ),
        migrations.AlterField(
            model_name='trait',
            name='type',
            field=models.CharField(blank=True, choices=[('ability_score', 'Ability Score Increase or Decrease'), ('skill_proficiency', 'Skill Proficiency'), ('tool_proficiency', 'Tool Proficiency'), ('language', 'Language'), ('equipment', 'Equipment'), ('feature', 'Feature'), ('suggested_characteristics', 'Suggested Characteristics'), ('adventures_and_advancement', 'Adventures and Advancement'), ('connection_and_memento', 'Connection and Memento')], help_text='Modification type.', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='BackgroundBenefit',
        ),
        migrations.DeleteModel(
            name='FeatBenefit',
        ),
    ]
