# Generated by Django 5.1.2 on 2025-04-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0028_alter_creature_armor_detail_alter_item_armor_detail'),
        ('api_v2', '0030_creatureaction_order'),
        ('api_v2', '0030_merge_0028_condition_icon_0029_merge_20250407_1910'),
    ]

    operations = [
    ]
