# Generated by Django 3.2.20 on 2024-02-09 20:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0030_auto_20231106_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('level', models.IntegerField(help_text='Integer representing the minimum slot level required by the spell. Cantrip is 0.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('target_type', models.TextField(choices=[('creature', 'Creature'), ('object', 'Object'), ('point', 'Point'), ('area', 'Area')], help_text='Choices for spell targets.')),
                ('range', models.TextField(choices=[('self', 'Self'), ('touch', 'Touch'), ('special', 'special'), ('10', '10 feet'), ('25', '25 feet'), ('30', '30 feet'), ('60', '60 feet'), ('90', '90 feet'), ('100', '100 feet'), ('120', '120 feet'), ('150', '150 feet'), ('180', '180 feet'), ('300', '300 feet'), ('500', '500 feet'), ('1mile', '1 mile'), ('100miles', '100 miles'), ('sight', 'Sight')], help_text='Choices for spell targets.')),
                ('ritual', models.BooleanField(default=False, help_text='Whether or not the spell can be cast as a ritual.')),
                ('casting_time', models.TextField(choices=[('reaction', 'Reaction'), ('bonus-action', 'Bonus Action'), ('action', 'Action'), ('1minute', '1 Minute'), ('5minutes', '5 Minutes'), ('10minutes', '10 Minutes'), ('1hour', '1 Hour'), ('8hours', '8 Hours')], help_text="Casting time name, such as '1 action'")),
                ('verbal', models.BooleanField(default=False, help_text='Whether or not casting the spell requires a verbal component.')),
                ('somatic', models.BooleanField(default=False, help_text='Whether or not casting the spell requires a verbal component.')),
                ('material', models.BooleanField(default=False, help_text='Whether or not casting the spell requires a verbal component.')),
                ('material_specified', models.TextField(help_text='A short description of the material required for the spell.')),
                ('material_cost', models.TextField(help_text='The cost of the material.')),
                ('material_consumed', models.BooleanField(default=False, help_text='Whether or the material component is consumed during the casting.')),
                ('target_count', models.TextField()),
                ('saving_throw_ability', models.TextField()),
                ('attack_roll', models.BooleanField(default=False, help_text='Whether or not the spell effect requires an attack roll.')),
                ('damage_roll', models.TextField()),
                ('damage_types', models.JSONField(default=[], help_text='The types of damage done by the spell in a list.')),
                ('duration', models.TextField(help_text='Description of the duration of the effect such as "instantaneous" or "Up to 1 minute"')),
                ('shape_type', models.TextField(choices=[('cone', 'Cone'), ('cube', 'Cube'), ('cylinder', 'Cylinder'), ('line', 'Line'), ('sphere', 'sphere')], help_text='The shape of the area of effect.')),
                ('shape_magnitude', models.IntegerField(help_text='The magnitude of the shape (without units).', validators=[django.core.validators.MinValueValidator(0)])),
                ('concentration', models.BooleanField(default=False, help_text='Whether the effect requires concentration to be maintained.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
