# Generated by Django 3.2.20 on 2024-01-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0031_characterclass_feature_featureitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='hit_dice',
            field=models.CharField(blank=True, choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12'), ('d20', 'd20'), ('d100', 'd100')], default=None, help_text='Dice notation hit dice option.', max_length=100, null=True),
        ),
    ]
