# Generated by Django 3.2.20 on 2024-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0031_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='damage_types',
            field=models.JSONField(default=list, help_text='The types of damage done by the spell in a list.'),
        ),
    ]
