# Generated by Django 5.1.2 on 2025-04-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0031_merge_20250414_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='published_at',
            new_name='publication_date',
        ),
    ]
