# Generated by Django 3.2.20 on 2024-01-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0032_characterclass_hit_dice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='character_class',
            new_name='characterclass',
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='hit_dice',
            field=models.CharField(blank=True, choices=[('D4', 'd4'), ('D6', 'd6'), ('D8', 'd8'), ('D10', 'd10'), ('D12', 'd12'), ('D20', 'd20')], default=None, help_text='Dice notation hit dice option.', max_length=100, null=True),
        ),
    ]
