# Generated by Django 5.1.2 on 2025-04-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0032_rename_published_at_document_publication_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Race',
            new_name='Species',
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
    ]
