# Generated by Django 3.2.20 on 2024-02-16 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0033_alter_spell_saving_throw_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='damage_roll',
            field=models.TextField(blank=True, help_text='The damage roll for the field in dice notaion. Empty string if no roll.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='material_specified',
            field=models.TextField(blank=True, help_text='A short description of the material required for the spell.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.TextField(choices=[('self', 'Self'), ('touch', 'Touch'), ('special', 'special'), ('5', '5 feet'), ('10', '10 feet'), ('15', '15 feet'), ('20', '20 feet'), ('25', '25 feet'), ('30', '30 feet'), ('40', '40 feet'), ('50', '50 feet'), ('60', '60 feet'), ('90', '90 feet'), ('100', '100 feet'), ('120', '120 feet'), ('150', '150 feet'), ('180', '180 feet'), ('200', '200 feet'), ('300', '300 feet'), ('400', '400 feet'), ('500', '500 feet'), ('1000', '1000 feet'), ('1mile', '1 mile'), ('5miles', '5 miles'), ('10miles', '10 miles'), ('100miles', '100 miles'), ('150miles', '150 miles'), ('500miles', '500 miles'), ('sight', 'Sight'), ('unlimited', 'Unlimited')], help_text='Choices for spell targets.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='saving_throw_ability',
            field=models.TextField(blank=True, help_text='Given the spell requires a saving throw, which ability is targeted. Empty string if no saving throw.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='shape_magnitude',
            field=models.IntegerField(blank=True, help_text='The magnitude of the shape (without units).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='shape_type',
            field=models.TextField(blank=True, choices=[('cone', 'Cone'), ('cube', 'Cube'), ('cylinder', 'Cylinder'), ('line', 'Line'), ('sphere', 'sphere')], help_text='The shape of the area of effect.'),
        ),
    ]
