# Generated by Django 5.1.2 on 2025-04-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0033_rename_race_species_alter_species_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaceTrait',
            new_name='SpeciesTrait',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='subrace_of',
            new_name='subspecies_of',
        ),
    ]
