# Generated by Django 5.1.2 on 2025-04-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0034_rename_racetrait_speciestrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('feet', 'feet'), ('miles', 'miles')], help_text='What distance unit the relevant field uses.', max_length=20, null=True),
        ),
    ]
