# Generated by Django 3.2.20 on 2024-02-16 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0034_auto_20240216_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='shape_magnitude',
            field=models.IntegerField(help_text='The magnitude of the shape (without units).', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='shape_type',
            field=models.TextField(choices=[('cone', 'Cone'), ('cube', 'Cube'), ('cylinder', 'Cylinder'), ('line', 'Line'), ('sphere', 'sphere')], help_text='The shape of the area of effect.', null=True),
        ),
    ]
