# Generated by Django 5.1.2 on 2025-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0035_document_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.TextField(default='', help_text='A short textual description of the image. Important for accessibility'),
        ),
    ]
