# Generated by Django 5.1.2 on 2025-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0035_document_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='damage_vulnerabilities_display',
            field=models.CharField(blank=True, help_text="The Creature's damage vulnerabilities, formatted in a human-readable string", max_length=128, null=True),
        ),
    ]
