# Generated by Django 5.1.2 on 2025-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0036_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.TextField(help_text='A short textual description of the image. Important for accessibility'),
        ),
    ]
