# Generated by Django 3.2.20 on 2024-02-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0036_auto_20240217_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.TextField(choices=[('reaction', 'Reaction'), ('bonus-action', '1 Bonus Action'), ('action', '1 Action'), ('1minute', '1 Minute'), ('5minutes', '5 Minutes'), ('10minutes', '10 Minutes'), ('1hour', '1 Hour'), ('8hours', '8 Hours')], help_text="Casting time name, such as '1 action'"),
        ),
        migrations.CreateModel(
            name='CastingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('default', 'Default'), ('ritual', 'Ritual'), ('player_level_1', 'Player Level 1'), ('player_level_2', 'Player Level 2'), ('player_level_3', 'Player Level 3'), ('player_level_4', 'Player Level 4'), ('player_level_5', 'Player Level 5'), ('player_level_6', 'Player Level 6'), ('player_level_7', 'Player Level 7'), ('player_level_8', 'Player Level 8'), ('player_level_9', 'Player Level 9'), ('player_level_10', 'Player Level 10'), ('player_level_11', 'Player Level 11'), ('player_level_12', 'Player Level 12'), ('player_level_13', 'Player Level 13'), ('player_level_14', 'Player Level 14'), ('player_level_15', 'Player Level 15'), ('player_level_16', 'Player Level 16'), ('player_level_17', 'Player Level 17'), ('player_level_18', 'Player Level 18'), ('player_level_19', 'Player Level 19'), ('player_level_20', 'Player Level 20'), ('slot_level_1', 'Spell Slot Level 1'), ('slot_level_2', 'Spell SlotLevel 2'), ('slot_level_3', 'Spell Slot Level 3'), ('slot_level_4', 'Spell Slot Level 4'), ('slot_level_5', 'Spell Slot Level 5'), ('slot_level_6', 'Spell Slot Level 6'), ('slot_level_7', 'Spell Slot Level 7'), ('slot_level_8', 'Spell Slot Level 8'), ('slot_level_9', 'Spell Slot Level 9')])),
                ('damage_roll', models.TextField(help_text="The damage roll for the field in dice notaion. Null if options don't affect damage roll.", null=True)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.spell')),
            ],
        ),
    ]
