# Generated by Django 5.1.2 on 2025-05-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0036_creature_damage_vulnerabilities_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='damage_vulnerabilities_display',
            field=models.CharField(blank=True, default='', help_text="The Creature's damage vulnerabilities, formatted in a human-readable string", max_length=128, null=True),
        ),
    ]
