# Generated by Django 5.1.2 on 2025-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0037_alter_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='attribution',
            field=models.TextField(default='', help_text='Attribution information for this image. Who drew it and where we can find more of thier work?'),
        ),
    ]
