# Generated by Django 5.1.2 on 2025-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0037_alter_creature_damage_vulnerabilities_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='damage_immunities_display',
            field=models.CharField(blank=True, default='', help_text="The Creature's damage immunities, formatted as a human-readable string", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='damage_resistances_display',
            field=models.CharField(blank=True, default='', help_text="The Creature's damage resistances, formatted as a human-readable string", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='damage_vulnerabilities_display',
            field=models.CharField(blank=True, default='', help_text="The Creature's damage vulnerabilities, formatted as a human-readable string", max_length=128, null=True),
        ),
    ]
