# Generated by Django 3.2.20 on 2024-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0037_auto_20240217_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingoption',
            name='duration',
            field=models.TextField(default='', help_text='Description of the duration of the effect such as "instantaneous" or "Up to 1 minute"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castingoption',
            name='range',
            field=models.TextField(default='', help_text='asdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castingoption',
            name='target_count',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='castingoption',
            name='damage_roll',
            field=models.TextField(help_text="The damage roll for the field in dice notation. Null if options don't affect damage roll.", null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='damage_roll',
            field=models.TextField(blank=True, help_text='The damage roll for the field in dice notation. Empty string if no roll.'),
        ),
    ]
