# Generated by Django 5.1.2 on 2025-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0038_image_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='attribution',
            field=models.TextField(help_text='Attribution information for this image. Who drew it and where we can find more of thier work?'),
        ),
    ]
