# Generated by Django 5.1.2 on 2025-05-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0038_creature_damage_immunities_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='condition_immunity_display',
            field=models.CharField(blank=True, default='', help_text="The Creature's condition immunities, formatted as a human-readable string", max_length=128, null=True),
        ),
    ]
