# Generated by Django 3.2.20 on 2024-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0038_auto_20240222_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingoption',
            name='duration',
            field=models.TextField(help_text='Description of the duration of the effect such as "instantaneous" or "Up to 1 minute"', null=True),
        ),
        migrations.AlterField(
            model_name='castingoption',
            name='range',
            field=models.TextField(help_text='asdf', null=True),
        ),
        migrations.AlterField(
            model_name='castingoption',
            name='target_count',
            field=models.TextField(help_text='The count of targets for this casting of the spell.', null=True),
        ),
    ]
