# Generated by Django 3.2.20 on 2024-02-28 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0039_auto_20240225_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.TextField(choices=[('reaction', 'Reaction'), ('bonus-action', '1 Bonus Action'), ('action', '1 Action'), ('1minute', '1 Minute'), ('5minutes', '5 Minutes'), ('10minutes', '10 Minutes'), ('1hour', '1 Hour'), ('8hours', '8 Hours')], help_text="Casting time key, such as 'action'"),
        ),
        migrations.AlterField(
            model_name='spell',
            name='higher_level',
            field=models.TextField(help_text='Description of casting the spell at a different level.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.IntegerField(help_text='Integer representing the default slot level required by the spell.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='spell',
            name='material_cost',
            field=models.TextField(help_text='Cost of the material. Null if no cost specified'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='material_specified',
            field=models.TextField(blank=True, help_text='Description of the material specified for the spell.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.TextField(choices=[('self', 'Self'), ('touch', 'Touch'), ('special', 'special'), ('5', '5 feet'), ('10', '10 feet'), ('15', '15 feet'), ('20', '20 feet'), ('25', '25 feet'), ('30', '30 feet'), ('40', '40 feet'), ('50', '50 feet'), ('60', '60 feet'), ('90', '90 feet'), ('100', '100 feet'), ('120', '120 feet'), ('150', '150 feet'), ('180', '180 feet'), ('200', '200 feet'), ('300', '300 feet'), ('400', '400 feet'), ('500', '500 feet'), ('1000', '1000 feet'), ('1mile', '1 mile'), ('5miles', '5 miles'), ('10miles', '10 miles'), ('100miles', '100 miles'), ('150miles', '150 miles'), ('500miles', '500 miles'), ('sight', 'Sight'), ('unlimited', 'Unlimited')], help_text='Spell target range key.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.TextField(choices=[('abjuration', 'Abjuration'), ('conjuration', 'Conjuration'), ('divination', 'Divination'), ('enchantment', 'Enchantment'), ('evocation', 'Evocation'), ('illusion', 'Illusion'), ('necromancy', 'Necromancy'), ('transmutation', 'Transmutaion')], help_text="Spell school key, such as 'evocation'"),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target_count',
            field=models.TextField(help_text='Description '),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target_type',
            field=models.TextField(choices=[('creature', 'Creature'), ('object', 'Object'), ('point', 'Point'), ('area', 'Area')], help_text='Spell target type key.'),
        ),
    ]
