# Generated by Django 5.1.2 on 2025-05-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0039_creature_condition_immunity_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='condition_immunity_display',
            new_name='condition_immunities_display',
        ),
    ]
