# Generated by Django 3.2.20 on 2024-02-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0040_auto_20240228_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='material_cost',
            new_name='material_cost_txt',
        ),
    ]
