# Generated by Django 5.1.2 on 2025-05-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0039_alter_image_attribution'),
        ('api_v2', '0040_rename_condition_immunity_display_creature_condition_immunities_display'),
    ]

    operations = [
    ]
