# Generated by Django 5.2.1 on 2025-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0041_merge_20250509_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionConcept',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('key', models.CharField(help_text="Unique key for the condition concept (e.g., 'invisible').", max_length=100, primary_key=True, serialize=False)),
                ('conditions', models.ManyToManyField(help_text='All condition implementations that are equivalent to this concept.', related_name='concepts', to='api_v2.condition')),
            ],
            options={
                'verbose_name': 'condition concept',
                'verbose_name_plural': 'condition concepts',
                'ordering': ['name'],
            },
        ),
    ]
