# Generated by Django 5.1.2 on 2025-05-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0041_merge_20250509_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ruleset',
            options={'ordering': ['name']},
        ),
    ]
