# Generated by Django 3.2.20 on 2024-02-28 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0041_rename_material_cost_spell_material_cost_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='material_cost',
            field=models.IntegerField(blank=True, help_text='Cost of the material. Null if no cost specified', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
