# Generated by Django 5.1.2 on 2025-05-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0042_alter_image_options_alter_rule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='ruleset',
            options={'ordering': ['key']},
        ),
    ]
