# Generated by Django 5.1.2 on 2025-05-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0042_weaponproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weaponproperty',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Weapon Properties'},
        ),
        migrations.CreateModel(
            name='WeaponPropertyAssignment',
            fields=[
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, max_length=32, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='api_v2.weaponproperty')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api_v2.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
