# Generated by Django 5.1.2 on 2025-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0043_alter_weaponproperty_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='is_finesse',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_heavy',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_lance',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_light',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_net',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_thrown',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_two_handed',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='reach',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='requires_ammunition',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='requires_loading',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='versatile_dice',
        ),
    ]
