# Generated by Django 5.1.2 on 2025-05-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0043_alter_image_options_alter_rule_options_and_more'),
        ('api_v2', '0044_remove_weapon_is_finesse_remove_weapon_is_heavy_and_more'),
    ]

    operations = [
    ]
