# Generated by Django 5.1.2 on 2025-05-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0045_merge_20250520_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='primary_abilities',
            field=models.ManyToManyField(help_text='Primary abilities for thie class', to='api_v2.ability'),
        ),
        migrations.AddField(
            model_name='creature',
            name='proficiency_bonus',
            field=models.SmallIntegerField(help_text="The Creauture's Proficiency Bonus", null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ORIGIN', 'Origin'), ('FIGHTING_STYLE', 'Fighting Style'), ('EPIC_BOON', 'Epic Boon')], default='GENERAL', max_length=32),
        ),
        migrations.AddField(
            model_name='weaponproperty',
            name='type',
            field=models.CharField(blank=True, help_text='Weapon property type: ie. Weapon Mastery, etc.', max_length=32, null=True),
        ),
    ]
