# Generated by Django 5.2.1 on 2025-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0047_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='default', help_text='Name of the item.', max_length=100),
            preserve_default=False,
        ),
    ]
