# Generated by Django 3.2.20 on 2024-03-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0047_remove_spell_target_count_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castingoption',
            old_name='target_count',
            new_name='target_count_txt',
        ),
        migrations.AlterField(
            model_name='castingoption',
            name='damage_roll',
            field=models.TextField(blank=True, help_text='The damage roll for the field in dice notation. Empty string if no roll.', null=True),
        ),
    ]
