# Generated by Django 5.2.1 on 2025-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0048_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for the document, used for presentation purposes.', max_length=255, null=True),
        ),
    ]
