# Generated by Django 3.2.20 on 2024-03-01 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0048_auto_20240301_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingoption',
            name='target_count',
            field=models.IntegerField(help_text='Integer representing the count of targets.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
