# Generated by Django 5.2.1 on 2025-06-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0049_add_document_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='illustration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.image'),
        ),
    ]
