# Generated by Django 5.2.1 on 2025-06-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0042_add_condition_concept'),
        ('api_v2', '0049_add_document_display_name'),
    ]

    operations = [
    ]
