# Generated by Django 5.2.1 on 2025-06-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0049_add_document_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellcastingoption',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of complex casting option effects that cannot be captured in other fields.', null=True),
        ),
    ]
