# Generated by Django 3.2.20 on 2024-03-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0049_castingoption_target_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castingoption',
            name='target_count_txt',
        ),
    ]
