# Generated by Django 5.2.1 on 2025-06-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0050_merge_20250608_0235'),
        ('api_v2', '0050_spellcastingoption_desc'),
    ]

    operations = [
    ]
