# Generated by Django 3.2.20 on 2024-03-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0033_auto_20240123_0222'),
        ('api_v2', '0051_auto_20240301_2014'),
    ]

    operations = [
    ]
