# Generated by Django 5.2.1 on 2025-06-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0050_creature_illustration'),
        ('api_v2', '0051_merge_20250615_2056'),
    ]

    operations = [
    ]
