# Generated by Django 3.2.20 on 2024-03-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0052_merge_0033_auto_20240123_0222_0051_auto_20240301_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('rank', models.IntegerField(help_text='Ranking of the rarity, most common has the lowest values.', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
