# Generated by Django 5.2.1 on 2025-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0052_merge_20250615_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='background',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='backgroundbenefit',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='classfeature',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='conditionconcept',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='creatureaction',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='creaturetrait',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='creaturetype',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='damagetype',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='featbenefit',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='gamesystem',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='language',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='species',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='speciestrait',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='spellschool',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
        migrations.AlterField(
            model_name='weaponproperty',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
    ]
