# Generated by Django 3.2.20 on 2024-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0052_merge_0033_auto_20240123_0222_0051_auto_20240301_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_pk', models.CharField(max_length=255)),
                ('document_name', models.CharField(max_length=100)),
                ('object_pk', models.CharField(max_length=255)),
                ('object_name', models.CharField(max_length=100)),
                ('object_route', models.CharField(max_length=255)),
                ('schema_version', models.CharField(max_length=100)),
            ],
        ),
    ]
