# Generated by Django 3.2.20 on 2024-03-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0053_itemrarity_size_spellschool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='size',
            new_name='size_integer',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='size_integer',
        ),
    ]
