# Generated by Django 3.2.20 on 2024-03-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0053_searchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='highlighted',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='rank',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
    ]
