# Generated by Django 5.2.1 on 2025-09-01 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0055_remove_ability_desc_remove_skill_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='desc',
        ),
        migrations.CreateModel(
            name='AlignmentTypeDescription',
            fields=[
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('describes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.alignment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
