# Generated by Django 3.2.20 on 2024-03-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0056_auto_20240314_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.size'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.size'),
        ),
    ]
