# Generated by Django 5.2.1 on 2025-09-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0056_remove_alignment_desc_alignmenttypedescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlignmentTypeDescription',
            new_name='AlignmentDescription',
        ),
    ]
