# Generated by Django 3.2.20 on 2024-03-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0057_auto_20240314_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rarity',
            new_name='rarity_integer',
        ),
    ]
