# Generated by Django 5.2.1 on 2025-09-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0057_rename_alignmenttypedescription_alignmentdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConditionConcept',
        ),
    ]
