# Generated by Django 3.2.20 on 2024-03-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0058_rename_rarity_item_rarity_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.ForeignKey(help_text='Rarity object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.itemrarity'),
        ),
    ]
