# Generated by Django 5.2.1 on 2025-09-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0059_conditiondescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='desc',
        ),
    ]
