# Generated by Django 3.2.20 on 2024-03-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0059_item_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rarity_integer',
        ),
    ]
