# Generated by Django 3.2.20 on 2024-03-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0060_remove_item_rarity_integer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatureattack',
            old_name='damage_type',
            new_name='damage_type_OLD',
        ),
    ]
