# Generated by Django 5.2.1 on 2025-10-01 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0061_characterclass_desc_alter_abilitydescription_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciestrait',
            name='id',
        ),
        migrations.AddField(
            model_name='speciestrait',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
