# Generated by Django 5.2.1 on 2025-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0061_characterclass_desc_alter_abilitydescription_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeature',
            name='feature_type',
            field=models.CharField(choices=[('CORE_TRAITS_TABLE', 'CORE_TRAITS_TABLE'), ('CLASS_FEATURE', 'CLASS_FEATURE'), ('CLASS_TABLE_DATA', 'CLASS_TABLE_DATA'), ('PROFICIENCIES', 'PROFICIENCIES'), ('PROFICIENCY_BONUS', 'PROFICIENCY_BONUS'), ('SPELL_SLOTS', 'SPELL_SLOTS')], default='CLASS_FEATURE', help_text='The type that best represents this Class Feature', max_length=32),
        ),
    ]
