# Generated by Django 5.2.1 on 2025-10-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0061_characterclass_desc_alter_abilitydescription_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featbenefit',
            options={'ordering': ['parent', 'order']},
        ),
        migrations.RemoveField(
            model_name='featbenefit',
            name='id',
        ),
        migrations.AddField(
            model_name='featbenefit',
            name='key',
            field=models.CharField(default='', help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featbenefit',
            name='order',
            field=models.SmallIntegerField(blank=True, help_text='The position in the list of features that this feature appears in its source statblock', null=True),
        ),
    ]
