# Generated by Django 3.2.20 on 2024-03-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0062_creatureattack_damage_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatureattack',
            old_name='damage_type_OLD',
            new_name='extra_damage_type_OLD',
        ),
        migrations.RemoveField(
            model_name='creatureattack',
            name='extra_damage_type',
        ),
    ]
