# Generated by Django 5.2.1 on 2025-10-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0062_remove_speciestrait_id_speciestrait_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciestrait',
            name='order',
            field=models.SmallIntegerField(blank=True, help_text='The position in the list of features that a feature appears in its source statblock', null=True),
        ),
        migrations.AlterField(
            model_name='speciestrait',
            name='type',
            field=models.CharField(blank=True, choices=[('ABILITY_MODS', 'ABILITY_MODS'), ('SIZE', 'SIZE'), ('SPEED', 'SPEED')], max_length=16, null=True),
        ),
    ]
