# Generated by Django 5.2.1 on 2025-10-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0063_speciestrait_order_alter_speciestrait_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciestrait',
            options={'ordering': ['parent', 'order']},
        ),
    ]
