# Generated by Django 5.2.1 on 2025-10-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0062_alter_featbenefit_options_remove_featbenefit_id_and_more'),
        ('api_v2', '0064_alter_classfeature_feature_type'),
        ('api_v2', '0064_alter_speciestrait_options'),
    ]

    operations = [
    ]
