# Generated by Django 3.2.20 on 2024-03-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0064_auto_20240315_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatureattack',
            name='extra_damage_type_OLD',
        ),
    ]
