# Generated by Django 5.2.1 on 2025-10-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0065_merge_20251006_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeature',
            name='feature_type',
            field=models.CharField(choices=[('CORE_TRAITS_TABLE', 'CORE_TRAITS_TABLE'), ('CLASS_LEVEL_FEATURE', 'CLASS_LEVEL_FEATURE'), ('CLASS_FEATURE_OPTION_LIST', 'CLASS_FEATURE_OPTION_LIST'), ('CLASS_TABLE_DATA', 'CLASS_TABLE_DATA'), ('PROFICIENCIES', 'PROFICIENCIES'), ('PROFICIENCY_BONUS', 'PROFICIENCY_BONUS'), ('STARTING_EQUIPMENT', 'STARTING_EQUIPMENT'), ('SPELL_SLOTS', 'SPELL_SLOTS')], default='CLASS_LEVEL_FEATURE', help_text='The type that best represents this Class Feature', max_length=32),
        ),
    ]
