# Generated by Django 5.2.1 on 2025-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0066_alter_classfeature_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.TextField(choices=[('SOURCE', 'Source'), ('MISC', 'Miscellaneous')], default='SOURCE', help_text='Whether this Document is a published data source, or general resources'),
        ),
    ]
