# Generated by Django 5.2.1 on 2025-11-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0066_alter_classfeature_feature_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['index']},
        ),
    ]
