# Generated by Django 5.2.1 on 2025-11-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0066_alter_classfeature_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attunement_detail',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
