# Generated by Django 5.2.1 on 2025-11-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0066_alter_classfeature_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbenefit',
            name='type',
            field=models.CharField(blank=True, choices=[('ability_score', 'Ability Score Increase or Decrease'), ('skill_proficiency', 'Skill Proficiency'), ('tool_proficiency', 'Tool Proficiency'), ('language', 'Language'), ('equipment', 'Equipment'), ('feature', 'Feature'), ('feat', 'Feat'), ('suggested_characteristics', 'Suggested Characteristics'), ('adventures_and_advancement', 'Adventures and Advancement'), ('connection_and_memento', 'Connection and Memento')], help_text='Modification type.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creaturetrait',
            name='type',
            field=models.CharField(blank=True, choices=[('ability_score', 'Ability Score Increase or Decrease'), ('skill_proficiency', 'Skill Proficiency'), ('tool_proficiency', 'Tool Proficiency'), ('language', 'Language'), ('equipment', 'Equipment'), ('feature', 'Feature'), ('feat', 'Feat'), ('suggested_characteristics', 'Suggested Characteristics'), ('adventures_and_advancement', 'Adventures and Advancement'), ('connection_and_memento', 'Connection and Memento')], help_text='Modification type.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='featbenefit',
            name='type',
            field=models.CharField(blank=True, choices=[('ability_score', 'Ability Score Increase or Decrease'), ('skill_proficiency', 'Skill Proficiency'), ('tool_proficiency', 'Tool Proficiency'), ('language', 'Language'), ('equipment', 'Equipment'), ('feature', 'Feature'), ('feat', 'Feat'), ('suggested_characteristics', 'Suggested Characteristics'), ('adventures_and_advancement', 'Adventures and Advancement'), ('connection_and_memento', 'Connection and Memento')], help_text='Modification type.', max_length=200, null=True),
        ),
    ]
