# Generated by Django 5.2.1 on 2025-11-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0067_alter_rule_options'),
        ('api_v2', '0067_document_type'),
    ]

    operations = [
    ]
