# Generated by Django 3.2.20 on 2024-03-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0067_weapon_damage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='damage_type_old',
        ),
    ]
