# Generated by Django 3.2.20 on 2024-03-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0068_remove_weapon_damage_type_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='school',
            new_name='school_old',
        ),
    ]
