# Generated by Django 5.2.1 on 2025-11-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0067_alter_backgroundbenefit_type_and_more'),
        ('api_v2', '0068_merge_0067_alter_rule_options_0067_document_type'),
    ]

    operations = [
    ]
