# Generated by Django 5.2.1 on 2025-11-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0067_item_attunement_detail'),
        ('api_v2', '0069_merge_20251130_1921'),
    ]

    operations = [
    ]
