# Generated by Django 3.2.20 on 2024-03-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0069_rename_school_spell_school_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.ForeignKey(default='evocation', help_text="Spell school, such as 'evocation'", on_delete=django.db.models.deletion.CASCADE, to='api_v2.spellschool'),
            preserve_default=False,
        ),
    ]
