# Generated by Django 5.2.11 on 2026-03-06 23:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0071_convert_distance_fields_to_integer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='attunement_detail',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='requires_attunement',
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_immunities',
            field=models.ManyToManyField(related_name='%(class)s_damage_immunities', to='api_v2.damagetype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_resistances',
            field=models.ManyToManyField(related_name='%(class)s_damage_resistances', to='api_v2.damagetype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage_vulnerabilities',
            field=models.ManyToManyField(related_name='%(class)s_damage_vulnerabilities', to='api_v2.damagetype'),
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(blank=True, help_text='Description of the game content item. Markdown.')),
                ('cost', models.DecimalField(decimal_places=2, default=None, help_text='Number representing the cost of the object.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=3, default=0, help_text='Number representing the weight of the object.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('armor_class', models.IntegerField(default=0, help_text='Integer representing the armor class of the object.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('armor_detail', models.CharField(default='', help_text='Represents parathetical text that follows an objects AC', max_length=64, null=True)),
                ('hit_points', models.IntegerField(default=0, help_text='Integer representing the hit points of the object.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('hit_dice', models.TextField(blank=True, help_text='Dice string representing a way to calculate hit points.', null=True)),
                ('nonmagical_attack_resistance', models.BooleanField(default=False, help_text='If api_v2.models.object is resistant to nonmagical attacks.')),
                ('nonmagical_attack_immunity', models.BooleanField(default=False, help_text='If the api_v2.models.object is immune to nonmagical attacks.')),
                ('requires_attunement', models.BooleanField(default=False, help_text='If the item requires attunement.')),
                ('attunement_detail', models.CharField(blank=True, max_length=128, null=True)),
                ('armor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.armor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.itemcategory')),
                ('damage_immunities', models.ManyToManyField(related_name='%(class)s_damage_immunities', to='api_v2.damagetype')),
                ('damage_resistances', models.ManyToManyField(related_name='%(class)s_damage_resistances', to='api_v2.damagetype')),
                ('damage_vulnerabilities', models.ManyToManyField(related_name='%(class)s_damage_vulnerabilities', to='api_v2.damagetype')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
                ('rarity', models.ForeignKey(help_text='Rarity object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.itemrarity')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.size')),
                ('weapon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
