# Generated by Django 5.2.1 on 2026-02-14 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0071_convert_distance_fields_to_integer'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_key', models.CharField(help_text='Primary key of the source object (e.g. item key, spell key).', max_length=100)),
                ('reference_object_key', models.CharField(help_text='Primary key of the reference object.', max_length=100)),
                ('anchor', models.CharField(help_text="The text in the source's description to highlight and link to the reference.", max_length=100)),
                ('reference_content_type', models.ForeignKey(help_text='The model of the object this Crossreference points to.', on_delete=django.db.models.deletion.CASCADE, related_name='Crossreferences_as_reference', to='contenttypes.contenttype')),
                ('source_content_type', models.ForeignKey(help_text='The model of the object that contains the description.', on_delete=django.db.models.deletion.CASCADE, related_name='Crossreferences_as_source', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'crossreferences',
                'ordering': ['source_content_type', 'source_object_key', 'id'],
                'indexes': [models.Index(fields=['source_content_type', 'source_object_key'], name='api_v2_cros_source__44db64_idx'), models.Index(fields=['reference_content_type', 'reference_object_key'], name='api_v2_cros_referen_a96fe0_idx')],
            },
        ),
    ]
