# Generated by Django 5.2.12 on 2026-04-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0072_alter_item_options_remove_item_attunement_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='challenge_rating_decimal',
            new_name='challenge_rating',
        ),
    ]
