# Generated by Django 3.2.20 on 2024-04-03 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0072_merge_20240329_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='object_route',
            new_name='object_model',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='document_name',
        ),
    ]
