# Generated by Django 5.2.1

import django.db.models.deletion
from django.db import migrations, models


def backfill_crossreference_document(apps, schema_editor):
    CrossReference = apps.get_model("api_v2", "CrossReference")
    ContentType = apps.get_model("contenttypes", "ContentType")
    for cr in CrossReference.objects.select_related("source_content_type").iterator():
        model = cr.source_content_type.model_class()
        if model is None:
            continue
        try:
            obj = model.objects.get(pk=cr.source_object_key)
        except model.DoesNotExist:
            continue
        document = getattr(obj, "document", None)
        if document is None and hasattr(obj, "parent") and obj.parent_id is not None:
            document = getattr(obj.parent, "document", None)
        if document is None and hasattr(obj, "parent") and getattr(obj.parent, "parent_id", None) is not None:
            document = getattr(obj.parent.parent, "document", None)
        if document is not None:
            cr.document_id = document.pk
            cr.save(update_fields=["document_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("api_v2", "0072_crossreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="crossreference",
            name="document",
            field=models.ForeignKey(
                help_text="Document the source object belongs to (denormalized for filtering).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api_v2.document",
            ),
        ),
        migrations.RunPython(backfill_crossreference_document, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="crossreference",
            name="document",
            field=models.ForeignKey(
                help_text="Document the source object belongs to (denormalized for filtering).",
                on_delete=django.db.models.deletion.CASCADE,
                to="api_v2.document",
            ),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["document"], name="api_v2_cros_documen_idx"),
        ),
    ]
