# Generated by Django 5.2.12 on 2026-04-09 08:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0073_rename_challenge_rating_decimal_creature_challenge_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='challenge_rating',
            field=models.FloatField(help_text='Challenge Rating field as a decimal number.', validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('30'))]),
        ),
    ]
