# Generated by Django 3.2.20 on 2024-05-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0073_auto_20240403_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='background',
            new_name='parent',
        ),
    ]
