# Generated by Django 5.2.1 on 2026-02-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0073_crossreference_document'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crossreference',
            new_name='api_v2_cros_documen_7cb8b8_idx',
            old_name='api_v2_cros_documen_idx',
        ),
    ]
