# Generated by Django 5.2.1 on 2026-02-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0074_rename_api_v2_cros_documen_idx_api_v2_cros_documen_7cb8b8_idx'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossreference',
            name='reference_content_type',
            field=models.ForeignKey(help_text='The model of the object this CrossReference points to.', on_delete=django.db.models.deletion.CASCADE, related_name='crossreferences_as_reference', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='crossreference',
            name='source_content_type',
            field=models.ForeignKey(help_text='The model of the object that contains the description.', on_delete=django.db.models.deletion.CASCADE, related_name='crossreferences_as_source', to='contenttypes.contenttype'),
        ),
    ]
