# Generated by Django 5.2.1

from django.db import migrations, models

from api_v2.models.crossreference import _crossreference_key_for


def backfill_crossreference_key(apps, schema_editor):
    CrossReference = apps.get_model("api_v2", "CrossReference")
    seen = set()
    for cr in CrossReference.objects.order_by("id").iterator():
        base_key = _crossreference_key_for(
            cr.source_object_key, cr.anchor, cr.reference_object_key
        )
        key = base_key
        suffix = 1
        while key in seen:
            key = f"{base_key}_{suffix}"
            suffix += 1
        seen.add(key)
        cr.key = key
        cr.save(update_fields=["key"])


class Migration(migrations.Migration):

    dependencies = [
        ("api_v2", "0075_alter_crossreference_reference_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crossreference",
            name="key",
            field=models.CharField(
                help_text="Deterministic key: source_object_key_slugified_anchor_reference_object_key.",
                max_length=300,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_crossreference_key, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="crossreference",
            name="key",
            field=models.CharField(
                help_text="Deterministic key: source_object_key_slugified_anchor_reference_object_key.",
                max_length=300,
                null=False,
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="crossreference",
            name="id",
        ),
        migrations.AlterField(
            model_name="crossreference",
            name="key",
            field=models.CharField(
                help_text="Deterministic key: source_object_key_slugified_anchor_reference_object_key.",
                max_length=300,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
