# Generated by Django 5.2.1 on 2026-02-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0076_crossreference_key_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossreference',
            options={'ordering': ['source_content_type', 'source_object_key', 'key'], 'verbose_name_plural': 'crossreferences'},
        ),
    ]
