# Generated by Django 3.2.20 on 2024-05-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0078_rename_feature_classfeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classfeature',
            old_name='characterclass',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='classfeatureitem',
            old_name='feature',
            new_name='parent',
        ),
    ]
