# Generated by Django 5.2.14 on 2026-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0079_rename_creatureaction_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='target_type',
            field=models.TextField(blank=True, choices=[('creature', 'Creature'), ('object', 'Object'), ('point', 'Point'), ('area', 'Area')], help_text='Spell target type key.', null=True),
        ),
    ]
