# Generated by Django 3.2.20 on 2024-05-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0079_auto_20240525_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfeatureitem',
            name='id',
        ),
        migrations.AddField(
            model_name='classfeatureitem',
            name='key',
            field=models.CharField(default=1, help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
