# Generated by Django 3.2.20 on 2024-05-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0080_auto_20240525_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capability',
            new_name='FeatBenefit',
        ),
    ]
