# Generated by Django 5.2.14 on 2026-06-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0080_alter_spell_target_type_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the game content item. Markdown.'),
        ),
    ]
