# Generated by Django 3.2.20 on 2024-05-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0081_rename_capability_featbenefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featbenefit',
            old_name='feat',
            new_name='parent',
        ),
    ]
