# Generated by Django 3.2.20 on 2024-05-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0082_rename_feat_featbenefit_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trait',
            new_name='RaceTrait',
        ),
    ]
