# Generated by Django 3.2.20 on 2024-05-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0083_rename_trait_racetrait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racetrait',
            old_name='race',
            new_name='parent',
        ),
    ]
