# Generated by Django 3.2.20 on 2024-05-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0084_rename_race_racetrait_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CastingOption',
            new_name='SpellCastingOption',
        ),
    ]
