# Generated by Django 3.2.20 on 2024-05-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0085_rename_castingoption_spellcastingoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spellcastingoption',
            old_name='spell',
            new_name='parent',
        ),
    ]
