# Generated by Django 3.2.20 on 2024-06-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0086_rename_spell_spellcastingoption_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatureAttack',
            new_name='CreatureActionAttack',
        ),
    ]
