# Generated by Django 3.2.20 on 2024-05-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0086_rename_spell_spellcastingoption_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatureaction',
            name='document',
        ),
        migrations.AlterField(
            model_name='creatureaction',
            name='key',
            field=models.CharField(help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False),
        ),
    ]
