# Generated by Django 3.2.20 on 2024-05-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0087_auto_20240531_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatureaction',
            old_name='creature',
            new_name='parent',
        ),
    ]
