# Generated by Django 3.2.20 on 2024-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0087_rename_creatureattack_creatureactionattack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatureactionattack',
            name='document',
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='key',
            field=models.CharField(help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False),
        ),
    ]
