# Generated by Django 3.2.20 on 2024-05-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0088_rename_creature_creatureaction_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatureattack',
            old_name='creature_action',
            new_name='parent',
        ),
    ]
