# Generated by Django 3.2.20 on 2024-06-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0091_rename_creature_creatureaction_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('key', models.CharField(help_text='Unique key for the Item.', max_length=100, primary_key=True, serialize=False)),
                ('aquatic', models.BooleanField(default=False, help_text='Whether or not aquatic environment rules apply to this environment.')),
                ('planar', models.BooleanField(default=False, help_text='Whether or not this environment is a plane of existence.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
            ],
            options={
                'verbose_name_plural': 'environments',
            },
        ),
    ]
