# Generated by Django 3.2.20 on 2024-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0092_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stats_expected',
            field=models.JSONField(blank=True, help_text='JSON representation of expected object counts.', null=True),
        ),
    ]
