# Generated by Django 3.2.20 on 2024-06-18 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0093_document_stats_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='burrow',
            field=models.FloatField(help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='creature',
            name='climb',
            field=models.FloatField(help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='creature',
            name='fly',
            field=models.FloatField(help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='creature',
            name='hover',
            field=models.BooleanField(default=False, help_text='Whether or not the walk movement is hovering.'),
        ),
        migrations.AddField(
            model_name='creature',
            name='swim',
            field=models.FloatField(help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='creature',
            name='unit',
            field=models.CharField(choices=[('feet', 'feet')], help_text='What distance unit the relevant field uses.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='walk',
            field=models.FloatField(default=0, help_text='Used to measure distance.', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
