# Generated by Django 3.2.20 on 2024-06-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0094_auto_20240618_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='distance_unit',
            field=models.CharField(choices=[('feet', 'feet')], help_text='What distance unit the relevant field uses.', max_length=20, null=True),
        ),
    ]
