# Generated by Django 3.2.20 on 2024-06-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0096_alter_spell_shape_magnitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='shape_magnitude',
            new_name='shape_size',
        ),
    ]
