# Generated by Django 3.2.20 on 2024-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0097_rename_shape_magnitude_spell_shape_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='shape_size_unit',
            field=models.CharField(choices=[('feet', 'feet')], help_text='What distance unit the relevant field uses.', max_length=20, null=True),
        ),
    ]
