# Generated by Django 3.2.20 on 2024-06-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0098_spell_shape_size_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='range',
            new_name='range_text',
        ),
    ]
