# Generated by Django 3.2.20 on 2024-06-19 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0099_rename_range_spell_range_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.FloatField(help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='spell',
            name='range_unit',
            field=models.CharField(choices=[('feet', 'feet')], help_text='What distance unit the relevant field uses.', max_length=20, null=True),
        ),
    ]
