# Generated by Django 3.2.20 on 2024-07-02 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0101_auto_20240627_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='saving_throw_charisma',
            field=models.SmallIntegerField(blank=True, help_text='Signed integer added to charisma saving throws.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='saving_throw_constitution',
            field=models.SmallIntegerField(blank=True, help_text='Signed integer added to constitution saving throws.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='saving_throw_dexterity',
            field=models.SmallIntegerField(blank=True, help_text='Signed integer added to dexterity saving throws.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='saving_throw_intelligence',
            field=models.SmallIntegerField(blank=True, help_text='Signed integer added to intelligence saving throws.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='saving_throw_strength',
            field=models.SmallIntegerField(blank=True, help_text='Signed integer added to strength saving throws.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='saving_throw_wisdom',
            field=models.SmallIntegerField(blank=True, help_text='Signed integer added to wisdom saving throws.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
