# Generated by Django 3.2.20 on 2024-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0102_auto_20240707_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='condition_immunities',
            field=models.ManyToManyField(default=None, help_text='Conditions that this creature is immune to.', null=True, to='api_v2.Condition'),
        ),
        migrations.AddField(
            model_name='creature',
            name='damage_immunities',
            field=models.ManyToManyField(related_name='creature_damage_immunities', to='api_v2.DamageType'),
        ),
        migrations.AddField(
            model_name='creature',
            name='damage_resistances',
            field=models.ManyToManyField(related_name='creature_damage_resistances', to='api_v2.DamageType'),
        ),
        migrations.AddField(
            model_name='creature',
            name='damage_vulnerabilities',
            field=models.ManyToManyField(related_name='creature_damage_vulnerabilities', to='api_v2.DamageType'),
        ),
        migrations.AddField(
            model_name='creature',
            name='nonmagical_attack_immunity',
            field=models.BooleanField(default=False, help_text='If the api_v2.models.object is immune to nonmagical attacks.'),
        ),
        migrations.AddField(
            model_name='creature',
            name='nonmagical_attack_resistance',
            field=models.BooleanField(default=False, help_text='If api_v2.models.object is resistant to nonmagical attacks.'),
        ),
        migrations.AddField(
            model_name='item',
            name='damage_immunities',
            field=models.ManyToManyField(related_name='item_damage_immunities', to='api_v2.DamageType'),
        ),
        migrations.AddField(
            model_name='item',
            name='damage_resistances',
            field=models.ManyToManyField(related_name='item_damage_resistances', to='api_v2.DamageType'),
        ),
        migrations.AddField(
            model_name='item',
            name='damage_vulnerabilities',
            field=models.ManyToManyField(related_name='item_damage_vulnerabilities', to='api_v2.DamageType'),
        ),
        migrations.AddField(
            model_name='item',
            name='nonmagical_attack_immunity',
            field=models.BooleanField(default=False, help_text='If the api_v2.models.object is immune to nonmagical attacks.'),
        ),
        migrations.AddField(
            model_name='item',
            name='nonmagical_attack_resistance',
            field=models.BooleanField(default=False, help_text='If api_v2.models.object is resistant to nonmagical attacks.'),
        ),
    ]
