# Generated by Django 3.2.20 on 2024-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0103_auto_20240707_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='condition_immunities',
            field=models.ManyToManyField(help_text='Conditions that this creature is immune to.', to='api_v2.Condition'),
        ),
    ]
