# Generated by Django 3.2.20 on 2024-07-12 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0105_auto_20240709_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='languages',
            field=models.ManyToManyField(to='api_v2.Language'),
        ),
        migrations.AddField(
            model_name='creature',
            name='languages_desc',
            field=models.TextField(default='[None provided]', help_text='Description of the languages item.'),
        ),
        migrations.AddField(
            model_name='creature',
            name='telepathy_range',
            field=models.FloatField(blank=True, help_text='Used to measure distance.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
