# Generated by Django 3.2.20 on 2024-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0106_auto_20240712_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='languages_desc',
            field=models.TextField(blank=True, default='[None provided]', help_text='Description of the languages item.'),
        ),
    ]
