# Generated by Django 3.2.20 on 2024-07-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0107_alter_creature_languages_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('type', models.CharField(blank=True, choices=[('ability_score', 'Ability Score Increase or Decrease'), ('skill_proficiency', 'Skill Proficiency'), ('tool_proficiency', 'Tool Proficiency'), ('language', 'Language'), ('equipment', 'Equipment'), ('feature', 'Feature'), ('suggested_characteristics', 'Suggested Characteristics'), ('adventures_and_advancement', 'Adventures and Advancement'), ('connection_and_memento', 'Connection and Memento')], help_text='Modification type.', max_length=200, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.creature')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
