# Generated by Django 3.2.20 on 2024-07-30 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0108_creaturetrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='passive_perception',
            field=models.SmallIntegerField(default=0, help_text='Integer representing the passive perception ability.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
