# Generated by Django 3.2.20 on 2024-08-04 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0110_auto_20240804_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='ability_score_charisma',
            field=models.SmallIntegerField(default=0, help_text='Integer representing the charisma ability.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='ability_score_constitution',
            field=models.SmallIntegerField(default=0, help_text='Integer representing the constitution ability.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='ability_score_dexterity',
            field=models.SmallIntegerField(default=0, help_text='Integer representing the dexterity ability.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='ability_score_intelligence',
            field=models.SmallIntegerField(default=0, help_text='Integer representing the intelligence ability.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='ability_score_strength',
            field=models.SmallIntegerField(default=0, help_text='Integer representing the strength ability.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='ability_score_wisdom',
            field=models.SmallIntegerField(default=0, help_text='Integer representing the wisdom ability.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='creature',
            name='experience_points_integer',
            field=models.IntegerField(blank=True, help_text='Optional override for calculated XP based on CR.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
