# Generated by Django 3.2.20 on 2024-08-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0112_ability_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellSet',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('key', models.CharField(help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False)),
                ('spells', models.ManyToManyField(help_text='The set of spells.', related_name='spellsets', to='api_v2.Spell')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
