# Generated by Django 3.2.20 on 2024-08-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0112_ability_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='classes',
            field=models.ManyToManyField(to='api_v2.CharacterClass'),
        ),
    ]
