# Generated by Django 3.2.20 on 2024-09-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0113_spell_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureaction',
            name='uses_param',
            field=models.SmallIntegerField(blank=True, help_text='The parameter X for if the action is limited.', null=True),
        ),
    ]
