# Generated by Django 3.2.20 on 2024-09-14 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0114_alter_creatureaction_uses_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureaction',
            name='uses_type',
            field=models.CharField(blank=True, choices=[('PER_DAY', 'X/Day'), ('RECHARGE_ON_ROLL', 'Recharge X-6'), ('RECHARGE_AFTER_REST', 'Recharge after a Short or Long rest')], help_text='How use of the action is limited, if at all.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='damage_bonus',
            field=models.SmallIntegerField(blank=True, help_text='Damage roll modifier.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='extra_damage_bonus',
            field=models.SmallIntegerField(blank=True, help_text='Damage roll modifier.', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='long_range_ft',
            field=models.SmallIntegerField(blank=True, help_text='Long range for ranged attacks, in feet.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='range_ft',
            field=models.SmallIntegerField(blank=True, help_text='Normal range for ranged attacks, in feet.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='reach_ft',
            field=models.SmallIntegerField(blank=True, help_text='Reach for melee attacks, in feet.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
