# Generated by Django 3.2.20 on 2024-09-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0114_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='id',
        ),
        migrations.AddField(
            model_name='rule',
            name='key',
            field=models.CharField(default='', help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
