# Generated by Django 3.2.20 on 2024-09-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0115_auto_20240925_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='api_v2.rule'),
        ),
    ]
