# Generated by Django 3.2.20 on 2024-09-14 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0115_auto_20240914_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureactionattack',
            name='damage_die_count',
            field=models.SmallIntegerField(blank=True, help_text='The number of dice to roll for damage.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='damage_die_type',
            field=models.CharField(blank=True, choices=[('D4', 'd4'), ('D6', 'd6'), ('D8', 'd8'), ('D10', 'd10'), ('D12', 'd12'), ('D20', 'd20')], help_text='What kind of die to roll for damage.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='extra_damage_die_count',
            field=models.SmallIntegerField(blank=True, help_text='The number of dice to roll for damage.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='extra_damage_die_type',
            field=models.CharField(blank=True, choices=[('D4', 'd4'), ('D6', 'd6'), ('D8', 'd8'), ('D10', 'd10'), ('D12', 'd12'), ('D20', 'd20')], help_text='What kind of die to roll for damage.', max_length=20, null=True),
        ),
    ]
