# Generated by Django 3.2.20 on 2024-09-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0116_alter_rule_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api_v2.document'),
            preserve_default=False,
        ),
    ]
