# Generated by Django 3.2.20 on 2024-09-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0116_auto_20240914_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creaturetrait',
            name='id',
        ),
        migrations.AddField(
            model_name='creaturetrait',
            name='key',
            field=models.CharField(default='a', help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='damage_type',
            field=models.ForeignKey(blank=True, help_text='What kind of damage this attack deals', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api_v2.damagetype'),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='extra_damage_type',
            field=models.ForeignKey(blank=True, help_text='What kind of extra damage this attack deals', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api_v2.damagetype'),
        ),
    ]
