# Generated by Django 3.2.20 on 2024-10-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0117_rule_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='next',
        ),
        migrations.AddField(
            model_name='rule',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('name', models.CharField(help_text='Name of the item.', max_length=100)),
                ('desc', models.TextField(help_text='Description of the game content item. Markdown.')),
                ('key', models.CharField(help_text='Unique key for the Document.', max_length=100, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='ruleset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api_v2.rulegroup'),
            preserve_default=False,
        ),
    ]
