# Generated by Django 3.2.20 on 2024-09-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0117_auto_20240922_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatureaction',
            name='form_condition',
            field=models.CharField(blank=True, default=None, help_text='Description of form-based conditions for this action.', max_length=100, null=True),
        ),
    ]
