# Generated by Django 3.2.20 on 2024-09-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0118_creatureaction_form_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatureaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('ACTION', 'Action'), ('REACTION', 'Reaction'), ('BONUS_ACTION', 'Bonus Action')], default='ACTION', help_text='How use of the action is limited, if at all.', max_length=20, null=True),
        ),
    ]
