# Generated by Django 3.2.20 on 2024-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0120_auto_20240928_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('ACTION', 'Action'), ('REACTION', 'Reaction'), ('BONUS_ACTION', 'Bonus Action'), ('LEGENDARY_ACTION', 'Legendary Action'), ('LAIR_ACTION', 'Lair Action')], default='ACTION', help_text='The type of action used.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creatureaction',
            name='legendary_cost',
            field=models.SmallIntegerField(blank=True, default=None, help_text='0 if not legendary, else, the number of legendary actions this costs.', null=True),
        ),
    ]
