# Generated by Django 3.2.20 on 2024-10-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0119_creature_subcategory'),
        ('api_v2', '0122_auto_20240929_2135'),
    ]

    operations = [
    ]
