# Generated by Django 5.1.2 on 2025-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_pk', models.CharField(max_length=255)),
                ('object_pk', models.CharField(max_length=255)),
                ('object_name', models.CharField(max_length=100)),
                ('object_model', models.CharField(max_length=255)),
                ('schema_version', models.CharField(max_length=100)),
                ('rank', models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('highlighted', models.TextField(default=None, null=True)),
            ],
        ),
    ]
