name: Clear Cloudflare Cache After Deployments

on:
  push:
    branches:
      - main
      - staging

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Make script executable
        run: chmod +x scripts/clear_cloudflare_cache.sh

      - name: Run cache clearing script
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: ./scripts/clear_cloudflare_cache.sh "${{ github.sha }}"